# Build vim from source with python3 support and execute tests.
branches:
  only:
    - dev
before_install:
    - export ORIGINAL_FOLDER=$PWD
    # Install dependencies.
    - sudo apt-get install tree python3-pip
    - sudo pip3 install --upgrade requests beautifulsoup4 setuptools
    # Install vim.
    - sudo apt-get install libncurses5-dev libgnome2-dev libgnomeui-dev libgtk2.0-dev libatk1.0-dev libbonoboui2-dev libcairo2-dev libx11-dev libxpm-dev libxt-dev python-dev python3-dev lua5.1 lua5.1-dev libperl-dev git
    - sudo apt-get remove vim vim-runtime gvim
    - cd /tmp
    - git clone --depth 1 https://github.com/vim/vim.git
    - cd vim
    - ./configure --with-features=huge --enable-multibyte --enable-python3interp=yes --with-python3-config-dir=/usr/lib/python3.5/config --enable-perlinterp=yes --enable-luainterp=yes --enable-gui=gtk2 --enable-cscope --prefix=/usr/local
    - sudo make && sudo make install
    - cd $ORIGINAL_FOLDER
    - tree .
install: make install
script: vim --version && make download && make test && tree .

# vim: set fileformat=unix filetype=yaml nowrap :
